services:
  - type: web
    name: smart-reconciliation-system
    env: node
    region: oregon
    buildCommand: bash render-build.sh
    startCommand: cd server && NODE_ENV=production node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
